// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, Endpoint, HandlerFunction } from './types';

export { Metadata, Endpoint, HandlerFunction };

import retrieve_api_v2 from './api/v2/retrieve-api-v2';
import list_api_v2 from './api/v2/list-api-v2';
import retrieve_caller_identity_api_v2 from './api/v2/retrieve-caller-identity-api-v2';
import retrieve_openapi_json_api_v2 from './api/v2/retrieve-openapi-json-api-v2';
import retrieve_public_ip_list_api_v2 from './api/v2/retrieve-public-ip-list-api-v2';
import retrieve_tags_api_v2 from './api/v2/retrieve-tags-api-v2';
import retrieve_versions_api_v2 from './api/v2/retrieve-versions-api-v2';
import retrieve_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/retrieve-account-v2-api-relay-auto-configs';
import update_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/update-account-v2-api-relay-auto-configs';
import delete_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/delete-account-v2-api-relay-auto-configs';
import relay_auto_configs_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/relay-auto-configs-account-v2-api-relay-auto-configs';
import reset_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/reset-account-v2-api-relay-auto-configs';
import retrieve_relay_auto_configs_account_v2_api_relay_auto_configs from './api/v2/account/relay-auto-configs/retrieve-relay-auto-configs-account-v2-api-relay-auto-configs';
import retrieve_v2_api_applications from './api/v2/applications/retrieve-v2-api-applications';
import update_v2_api_applications from './api/v2/applications/update-v2-api-applications';
import list_v2_api_applications from './api/v2/applications/list-v2-api-applications';
import delete_v2_api_applications from './api/v2/applications/delete-v2-api-applications';
import update_applications_v2_api_versions from './api/v2/applications/versions/update-applications-v2-api-versions';
import list_applications_v2_api_versions from './api/v2/applications/versions/list-applications-v2-api-versions';
import delete_applications_v2_api_versions from './api/v2/applications/versions/delete-applications-v2-api-versions';
import retrieve_v2_api_approval_requests from './api/v2/approval-requests/retrieve-v2-api-approval-requests';
import update_v2_api_approval_requests from './api/v2/approval-requests/update-v2-api-approval-requests';
import delete_v2_api_approval_requests from './api/v2/approval-requests/delete-v2-api-approval-requests';
import apply_v2_api_approval_requests from './api/v2/approval-requests/apply-v2-api-approval-requests';
import approval_requests_v2_api_approval_requests from './api/v2/approval-requests/approval-requests-v2-api-approval-requests';
import retrieve_approval_requests_v2_api_approval_requests from './api/v2/approval-requests/retrieve-approval-requests-v2-api-approval-requests';
import reviews_v2_api_approval_requests from './api/v2/approval-requests/reviews-v2-api-approval-requests';
import create_v2_api_auditlog from './api/v2/auditlog/create-v2-api-auditlog';
import retrieve_v2_api_auditlog from './api/v2/auditlog/retrieve-v2-api-auditlog';
import list_v2_api_auditlog from './api/v2/auditlog/list-v2-api-auditlog';
import retrieve_extinctions_v2_api_code_refs from './api/v2/code-refs/retrieve-extinctions-v2-api-code-refs';
import create_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/create-code-refs-v2-api-repositories';
import retrieve_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/retrieve-code-refs-v2-api-repositories';
import update_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/update-code-refs-v2-api-repositories';
import list_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/list-code-refs-v2-api-repositories';
import delete_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/delete-code-refs-v2-api-repositories';
import branch_delete_tasks_code_refs_v2_api_repositories from './api/v2/code-refs/repositories/branch-delete-tasks-code-refs-v2-api-repositories';
import retrieve_repositories_code_refs_v2_api_branches from './api/v2/code-refs/repositories/branches/retrieve-repositories-code-refs-v2-api-branches';
import update_repositories_code_refs_v2_api_branches from './api/v2/code-refs/repositories/branches/update-repositories-code-refs-v2-api-branches';
import list_repositories_code_refs_v2_api_branches from './api/v2/code-refs/repositories/branches/list-repositories-code-refs-v2-api-branches';
import extinction_events_repositories_code_refs_v2_api_branches from './api/v2/code-refs/repositories/branches/extinction-events-repositories-code-refs-v2-api-branches';
import retrieve_code_refs_v2_api_statistics from './api/v2/code-refs/statistics/retrieve-code-refs-v2-api-statistics';
import list_code_refs_v2_api_statistics from './api/v2/code-refs/statistics/list-code-refs-v2-api-statistics';
import retrieve_v2_api_destinations from './api/v2/destinations/retrieve-v2-api-destinations';
import update_v2_api_destinations from './api/v2/destinations/update-v2-api-destinations';
import list_v2_api_destinations from './api/v2/destinations/list-v2-api-destinations';
import delete_v2_api_destinations from './api/v2/destinations/delete-v2-api-destinations';
import generate_warehouse_destination_key_pair_v2_api_destinations from './api/v2/destinations/generate-warehouse-destination-key-pair-v2-api-destinations';
import retrieve_projects_flag_links_v2_api_flags from './api/v2/flag-links/projects/flags/retrieve-projects-flag-links-v2-api-flags';
import update_projects_flag_links_v2_api_flags from './api/v2/flag-links/projects/flags/update-projects-flag-links-v2-api-flags';
import delete_projects_flag_links_v2_api_flags from './api/v2/flag-links/projects/flags/delete-projects-flag-links-v2-api-flags';
import retrieve_v2_api_flag_statuses from './api/v2/flag-statuses/retrieve-v2-api-flag-statuses';
import retrieve_v2_api_flags from './api/v2/flags/retrieve-v2-api-flags';
import update_v2_api_flags from './api/v2/flags/update-v2-api-flags';
import delete_v2_api_flags from './api/v2/flags/delete-v2-api-flags';
import copy_v2_api_flags from './api/v2/flags/copy-v2-api-flags';
import retrieve_dependent_flags_flags_v2_api_dependent_flags from './api/v2/flags/dependent-flags/retrieve-dependent-flags-flags-v2-api-dependent-flags';
import retrieve_flags_v2_api_expiring_targets from './api/v2/flags/expiring-targets/retrieve-flags-v2-api-expiring-targets';
import update_flags_v2_api_expiring_targets from './api/v2/flags/expiring-targets/update-flags-v2-api-expiring-targets';
import retrieve_flags_v2_api_expiring_user_targets from './api/v2/flags/expiring-user-targets/retrieve-flags-v2-api-expiring-user-targets';
import update_flags_v2_api_expiring_user_targets from './api/v2/flags/expiring-user-targets/update-flags-v2-api-expiring-user-targets';
import retrieve_flags_v2_api_triggers from './api/v2/flags/triggers/retrieve-flags-v2-api-triggers';
import update_flags_v2_api_triggers from './api/v2/flags/triggers/update-flags-v2-api-triggers';
import delete_flags_v2_api_triggers from './api/v2/flags/triggers/delete-flags-v2-api-triggers';
import list_flags_v2_api_release from './api/v2/flags/release/list-flags-v2-api-release';
import delete_all_flags_v2_api_release from './api/v2/flags/release/delete-all-flags-v2-api-release';
import patch_all_flags_v2_api_release from './api/v2/flags/release/patch-all-flags-v2-api-release';
import retrieve_integration_capabilities_v2_api_big_segment_store from './api/v2/integration-capabilities/big-segment-store/retrieve-integration-capabilities-v2-api-big-segment-store';
import update_integration_capabilities_v2_api_big_segment_store from './api/v2/integration-capabilities/big-segment-store/update-integration-capabilities-v2-api-big-segment-store';
import delete_integration_capabilities_v2_api_big_segment_store from './api/v2/integration-capabilities/big-segment-store/delete-integration-capabilities-v2-api-big-segment-store';
import retrieve_big_segment_store_integration_capabilities_v2_api_big_segment_store from './api/v2/integration-capabilities/big-segment-store/retrieve-big-segment-store-integration-capabilities-v2-api-big-segment-store';
import retrieve_integration_capabilities_v2_api_feature_store from './api/v2/integration-capabilities/feature-store/retrieve-integration-capabilities-v2-api-feature-store';
import update_integration_capabilities_v2_api_feature_store from './api/v2/integration-capabilities/feature-store/update-integration-capabilities-v2-api-feature-store';
import delete_integration_capabilities_v2_api_feature_store from './api/v2/integration-capabilities/feature-store/delete-integration-capabilities-v2-api-feature-store';
import retrieve_feature_store_integration_capabilities_v2_api_feature_store from './api/v2/integration-capabilities/feature-store/retrieve-feature-store-integration-capabilities-v2-api-feature-store';
import validate_integration_capabilities_v2_api_feature_store from './api/v2/integration-capabilities/feature-store/validate-integration-capabilities-v2-api-feature-store';
import retrieve_integration_capabilities_v2_api_flag_import from './api/v2/integration-capabilities/flag-import/retrieve-integration-capabilities-v2-api-flag-import';
import update_integration_capabilities_v2_api_flag_import from './api/v2/integration-capabilities/flag-import/update-integration-capabilities-v2-api-flag-import';
import delete_integration_capabilities_v2_api_flag_import from './api/v2/integration-capabilities/flag-import/delete-integration-capabilities-v2-api-flag-import';
import retrieve_flag_import_integration_capabilities_v2_api_flag_import from './api/v2/integration-capabilities/flag-import/retrieve-flag-import-integration-capabilities-v2-api-flag-import';
import trigger_integration_capabilities_v2_api_flag_import from './api/v2/integration-capabilities/flag-import/trigger-integration-capabilities-v2-api-flag-import';
import retrieve_v2_api_integration_configurations from './api/v2/integration-configurations/retrieve-v2-api-integration-configurations';
import update_v2_api_integration_configurations from './api/v2/integration-configurations/update-v2-api-integration-configurations';
import delete_v2_api_integration_configurations from './api/v2/integration-configurations/delete-v2-api-integration-configurations';
import retrieve_integration_configurations_v2_api_keys from './api/v2/integration-configurations/keys/retrieve-integration-configurations-v2-api-keys';
import update_integration_configurations_v2_api_keys from './api/v2/integration-configurations/keys/update-integration-configurations-v2-api-keys';
import retrieve_v2_api_integrations from './api/v2/integrations/retrieve-v2-api-integrations';
import update_v2_api_integrations from './api/v2/integrations/update-v2-api-integrations';
import delete_v2_api_integrations from './api/v2/integrations/delete-v2-api-integrations';
import create_v2_api_members from './api/v2/members/create-v2-api-members';
import retrieve_v2_api_members from './api/v2/members/retrieve-v2-api-members';
import update_v2_api_members from './api/v2/members/update-v2-api-members';
import list_v2_api_members from './api/v2/members/list-v2-api-members';
import delete_v2_api_members from './api/v2/members/delete-v2-api-members';
import patch_all_v2_api_members from './api/v2/members/patch-all-v2-api-members';
import teams_v2_api_members from './api/v2/members/teams-v2-api-members';
import retrieve_v2_api_metrics from './api/v2/metrics/retrieve-v2-api-metrics';
import update_v2_api_metrics from './api/v2/metrics/update-v2-api-metrics';
import delete_v2_api_metrics from './api/v2/metrics/delete-v2-api-metrics';
import create_oauth_v2_api_clients from './api/v2/oauth/clients/create-oauth-v2-api-clients';
import retrieve_oauth_v2_api_clients from './api/v2/oauth/clients/retrieve-oauth-v2-api-clients';
import update_oauth_v2_api_clients from './api/v2/oauth/clients/update-oauth-v2-api-clients';
import list_oauth_v2_api_clients from './api/v2/oauth/clients/list-oauth-v2-api-clients';
import delete_oauth_v2_api_clients from './api/v2/oauth/clients/delete-oauth-v2-api-clients';
import create_v2_api_projects from './api/v2/projects/create-v2-api-projects';
import retrieve_v2_api_projects from './api/v2/projects/retrieve-v2-api-projects';
import update_v2_api_projects from './api/v2/projects/update-v2-api-projects';
import list_v2_api_projects from './api/v2/projects/list-v2-api-projects';
import delete_v2_api_projects from './api/v2/projects/delete-v2-api-projects';
import update_projects_v2_api_context_kinds from './api/v2/projects/context-kinds/update-projects-v2-api-context-kinds';
import retrieve_context_kinds_projects_v2_api_context_kinds from './api/v2/projects/context-kinds/retrieve-context-kinds-projects-v2-api-context-kinds';
import create_projects_v2_api_environments from './api/v2/projects/environments/create-projects-v2-api-environments';
import retrieve_projects_v2_api_environments from './api/v2/projects/environments/retrieve-projects-v2-api-environments';
import update_projects_v2_api_environments from './api/v2/projects/environments/update-projects-v2-api-environments';
import list_projects_v2_api_environments from './api/v2/projects/environments/list-projects-v2-api-environments';
import delete_projects_v2_api_environments from './api/v2/projects/environments/delete-projects-v2-api-environments';
import api_key_projects_v2_api_environments from './api/v2/projects/environments/api-key-projects-v2-api-environments';
import mobile_key_projects_v2_api_environments from './api/v2/projects/environments/mobile-key-projects-v2-api-environments';
import retrieve_followers_projects_v2_api_environments from './api/v2/projects/environments/retrieve-followers-projects-v2-api-environments';
import retrieve_environments_projects_v2_api_context_attributes from './api/v2/projects/environments/context-attributes/retrieve-environments-projects-v2-api-context-attributes';
import retrieve_context_attributes_environments_projects_v2_api_context_attributes from './api/v2/projects/environments/context-attributes/retrieve-context-attributes-environments-projects-v2-api-context-attributes';
import retrieve_environments_projects_v2_api_context_instances from './api/v2/projects/environments/context-instances/retrieve-environments-projects-v2-api-context-instances';
import delete_environments_projects_v2_api_context_instances from './api/v2/projects/environments/context-instances/delete-environments-projects-v2-api-context-instances';
import search_environments_projects_v2_api_context_instances from './api/v2/projects/environments/context-instances/search-environments-projects-v2-api-context-instances';
import retrieve_environments_projects_v2_api_contexts from './api/v2/projects/environments/contexts/retrieve-environments-projects-v2-api-contexts';
import update_environments_projects_v2_api_contexts from './api/v2/projects/environments/contexts/update-environments-projects-v2-api-contexts';
import search_environments_projects_v2_api_contexts from './api/v2/projects/environments/contexts/search-environments-projects-v2-api-contexts';
import create_environments_projects_v2_api_experiments from './api/v2/projects/environments/experiments/create-environments-projects-v2-api-experiments';
import retrieve_environments_projects_v2_api_experiments from './api/v2/projects/environments/experiments/retrieve-environments-projects-v2-api-experiments';
import update_environments_projects_v2_api_experiments from './api/v2/projects/environments/experiments/update-environments-projects-v2-api-experiments';
import list_environments_projects_v2_api_experiments from './api/v2/projects/environments/experiments/list-environments-projects-v2-api-experiments';
import iterations_environments_projects_v2_api_experiments from './api/v2/projects/environments/experiments/iterations-environments-projects-v2-api-experiments';
import retrieve_results_experiments_environments_projects_v2_api_metric_groups from './api/v2/projects/environments/experiments/metric-groups/retrieve-results-experiments-environments-projects-v2-api-metric-groups';
import retrieve_results_experiments_environments_projects_v2_api_metrics from './api/v2/projects/environments/experiments/metrics/retrieve-results-experiments-environments-projects-v2-api-metrics';
import evaluate_environments_projects_v2_api_flags from './api/v2/projects/environments/flags/evaluate-environments-projects-v2-api-flags';
import create_environments_projects_v2_api_holdouts from './api/v2/projects/environments/holdouts/create-environments-projects-v2-api-holdouts';
import retrieve_environments_projects_v2_api_holdouts from './api/v2/projects/environments/holdouts/retrieve-environments-projects-v2-api-holdouts';
import update_environments_projects_v2_api_holdouts from './api/v2/projects/environments/holdouts/update-environments-projects-v2-api-holdouts';
import list_environments_projects_v2_api_holdouts from './api/v2/projects/environments/holdouts/list-environments-projects-v2-api-holdouts';
import evaluate_environments_projects_v2_api_segments from './api/v2/projects/environments/segments/evaluate-environments-projects-v2-api-segments';
import retrieve_experimentation_settings_projects_v2_api_experimentation_settings from './api/v2/projects/experimentation-settings/retrieve-experimentation-settings-projects-v2-api-experimentation-settings';
import update_experimentation_settings_projects_v2_api_experimentation_settings from './api/v2/projects/experimentation-settings/update-experimentation-settings-projects-v2-api-experimentation-settings';
import retrieve_flag_defaults_projects_v2_api_flag_defaults from './api/v2/projects/flag-defaults/retrieve-flag-defaults-projects-v2-api-flag-defaults';
import update_flag_defaults_projects_v2_api_flag_defaults from './api/v2/projects/flag-defaults/update-flag-defaults-projects-v2-api-flag-defaults';
import approval_requests_flag_copy_flags_projects_v2_api_environments from './api/v2/projects/flags/environments/approval-requests-flag-copy-flags-projects-v2-api-environments';
import migration_safety_issues_flags_projects_v2_api_environments from './api/v2/projects/flags/environments/migration-safety-issues-flags-projects-v2-api-environments';
import retrieve_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/retrieve-environments-flags-projects-v2-api-approval-requests';
import update_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/update-environments-flags-projects-v2-api-approval-requests';
import delete_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/delete-environments-flags-projects-v2-api-approval-requests';
import apply_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/apply-environments-flags-projects-v2-api-approval-requests';
import approval_requests_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/approval-requests-environments-flags-projects-v2-api-approval-requests';
import retrieve_approval_requests_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/retrieve-approval-requests-environments-flags-projects-v2-api-approval-requests';
import reviews_environments_flags_projects_v2_api_approval_requests from './api/v2/projects/flags/environments/approval-requests/reviews-environments-flags-projects-v2-api-approval-requests';
import update_environments_flags_projects_v2_api_followers from './api/v2/projects/flags/environments/followers/update-environments-flags-projects-v2-api-followers';
import list_environments_flags_projects_v2_api_followers from './api/v2/projects/flags/environments/followers/list-environments-flags-projects-v2-api-followers';
import delete_environments_flags_projects_v2_api_followers from './api/v2/projects/flags/environments/followers/delete-environments-flags-projects-v2-api-followers';
import retrieve_environments_flags_projects_v2_api_scheduled_changes from './api/v2/projects/flags/environments/scheduled-changes/retrieve-environments-flags-projects-v2-api-scheduled-changes';
import update_environments_flags_projects_v2_api_scheduled_changes from './api/v2/projects/flags/environments/scheduled-changes/update-environments-flags-projects-v2-api-scheduled-changes';
import delete_environments_flags_projects_v2_api_scheduled_changes from './api/v2/projects/flags/environments/scheduled-changes/delete-environments-flags-projects-v2-api-scheduled-changes';
import retrieve_scheduled_changes_environments_flags_projects_v2_api_scheduled_changes from './api/v2/projects/flags/environments/scheduled-changes/retrieve-scheduled-changes-environments-flags-projects-v2-api-scheduled-changes';
import scheduled_changes_environments_flags_projects_v2_api_scheduled_changes from './api/v2/projects/flags/environments/scheduled-changes/scheduled-changes-environments-flags-projects-v2-api-scheduled-changes';
import create_environments_flags_projects_v2_api_workflows from './api/v2/projects/flags/environments/workflows/create-environments-flags-projects-v2-api-workflows';
import retrieve_environments_flags_projects_v2_api_workflows from './api/v2/projects/flags/environments/workflows/retrieve-environments-flags-projects-v2-api-workflows';
import list_environments_flags_projects_v2_api_workflows from './api/v2/projects/flags/environments/workflows/list-environments-flags-projects-v2-api-workflows';
import delete_environments_flags_projects_v2_api_workflows from './api/v2/projects/flags/environments/workflows/delete-environments-flags-projects-v2-api-workflows';
import create_flags_projects_v2_api_release from './api/v2/projects/flags/release/create-flags-projects-v2-api-release';
import update_flags_projects_v2_api_release from './api/v2/projects/flags/release/update-flags-projects-v2-api-release';
import create_projects_v2_api_layers from './api/v2/projects/layers/create-projects-v2-api-layers';
import update_projects_v2_api_layers from './api/v2/projects/layers/update-projects-v2-api-layers';
import list_projects_v2_api_layers from './api/v2/projects/layers/list-projects-v2-api-layers';
import retrieve_projects_v2_api_metric_groups from './api/v2/projects/metric-groups/retrieve-projects-v2-api-metric-groups';
import update_projects_v2_api_metric_groups from './api/v2/projects/metric-groups/update-projects-v2-api-metric-groups';
import delete_projects_v2_api_metric_groups from './api/v2/projects/metric-groups/delete-projects-v2-api-metric-groups';
import metric_groups_projects_v2_api_metric_groups from './api/v2/projects/metric-groups/metric-groups-projects-v2-api-metric-groups';
import retrieve_metric_groups_projects_v2_api_metric_groups from './api/v2/projects/metric-groups/retrieve-metric-groups-projects-v2-api-metric-groups';
import retrieve_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/retrieve-projects-v2-api-release-pipelines';
import update_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/update-projects-v2-api-release-pipelines';
import delete_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/delete-projects-v2-api-release-pipelines';
import release_pipelines_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/release-pipelines-projects-v2-api-release-pipelines';
import retrieve_release_pipelines_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/retrieve-release-pipelines-projects-v2-api-release-pipelines';
import retrieve_releases_projects_v2_api_release_pipelines from './api/v2/projects/release-pipelines/retrieve-releases-projects-v2-api-release-pipelines';
import retrieve_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/retrieve-projects-v2-api-ai-configs';
import update_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/update-projects-v2-api-ai-configs';
import delete_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/delete-projects-v2-api-ai-configs';
import ai_configs_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/ai-configs-projects-v2-api-ai-configs';
import retrieve_ai_configs_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/retrieve-ai-configs-projects-v2-api-ai-configs';
import retrieve_metrics_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/retrieve-metrics-projects-v2-api-ai-configs';
import retrieve_metrics_by_variation_projects_v2_api_ai_configs from './api/v2/projects/ai-configs/retrieve-metrics-by-variation-projects-v2-api-ai-configs';
import create_ai_configs_projects_v2_api_variations from './api/v2/projects/ai-configs/variations/create-ai-configs-projects-v2-api-variations';
import retrieve_ai_configs_projects_v2_api_variations from './api/v2/projects/ai-configs/variations/retrieve-ai-configs-projects-v2-api-variations';
import update_ai_configs_projects_v2_api_variations from './api/v2/projects/ai-configs/variations/update-ai-configs-projects-v2-api-variations';
import delete_ai_configs_projects_v2_api_variations from './api/v2/projects/ai-configs/variations/delete-ai-configs-projects-v2-api-variations';
import retrieve_ai_configs_projects_v2_api_model_configs from './api/v2/projects/ai-configs/model-configs/retrieve-ai-configs-projects-v2-api-model-configs';
import delete_ai_configs_projects_v2_api_model_configs from './api/v2/projects/ai-configs/model-configs/delete-ai-configs-projects-v2-api-model-configs';
import model_configs_ai_configs_projects_v2_api_model_configs from './api/v2/projects/ai-configs/model-configs/model-configs-ai-configs-projects-v2-api-model-configs';
import retrieve_model_configs_ai_configs_projects_v2_api_model_configs from './api/v2/projects/ai-configs/model-configs/retrieve-model-configs-ai-configs-projects-v2-api-model-configs';
import create_model_configs_ai_configs_projects_v2_api_restricted from './api/v2/projects/ai-configs/model-configs/restricted/create-model-configs-ai-configs-projects-v2-api-restricted';
import delete_all_model_configs_ai_configs_projects_v2_api_restricted from './api/v2/projects/ai-configs/model-configs/restricted/delete-all-model-configs-ai-configs-projects-v2-api-restricted';
import create_v2_api_roles from './api/v2/roles/create-v2-api-roles';
import retrieve_v2_api_roles from './api/v2/roles/retrieve-v2-api-roles';
import update_v2_api_roles from './api/v2/roles/update-v2-api-roles';
import list_v2_api_roles from './api/v2/roles/list-v2-api-roles';
import delete_v2_api_roles from './api/v2/roles/delete-v2-api-roles';
import retrieve_v2_api_segments from './api/v2/segments/retrieve-v2-api-segments';
import update_v2_api_segments from './api/v2/segments/update-v2-api-segments';
import delete_v2_api_segments from './api/v2/segments/delete-v2-api-segments';
import create_segments_v2_api_contexts from './api/v2/segments/contexts/create-segments-v2-api-contexts';
import retrieve_segments_v2_api_contexts from './api/v2/segments/contexts/retrieve-segments-v2-api-contexts';
import create_segments_v2_api_exports from './api/v2/segments/exports/create-segments-v2-api-exports';
import retrieve_segments_v2_api_exports from './api/v2/segments/exports/retrieve-segments-v2-api-exports';
import create_segments_v2_api_imports from './api/v2/segments/imports/create-segments-v2-api-imports';
import retrieve_segments_v2_api_imports from './api/v2/segments/imports/retrieve-segments-v2-api-imports';
import create_segments_v2_api_users from './api/v2/segments/users/create-segments-v2-api-users';
import retrieve_segments_v2_api_users from './api/v2/segments/users/retrieve-segments-v2-api-users';
import retrieve_segments_v2_api_expiring_targets from './api/v2/segments/expiring-targets/retrieve-segments-v2-api-expiring-targets';
import update_segments_v2_api_expiring_targets from './api/v2/segments/expiring-targets/update-segments-v2-api-expiring-targets';
import retrieve_segments_v2_api_expiring_user_targets from './api/v2/segments/expiring-user-targets/retrieve-segments-v2-api-expiring-user-targets';
import update_segments_v2_api_expiring_user_targets from './api/v2/segments/expiring-user-targets/update-segments-v2-api-expiring-user-targets';
import create_v2_api_teams from './api/v2/teams/create-v2-api-teams';
import retrieve_v2_api_teams from './api/v2/teams/retrieve-v2-api-teams';
import update_v2_api_teams from './api/v2/teams/update-v2-api-teams';
import list_v2_api_teams from './api/v2/teams/list-v2-api-teams';
import delete_v2_api_teams from './api/v2/teams/delete-v2-api-teams';
import members_v2_api_teams from './api/v2/teams/members-v2-api-teams';
import patch_all_v2_api_teams from './api/v2/teams/patch-all-v2-api-teams';
import retrieve_maintainers_v2_api_teams from './api/v2/teams/retrieve-maintainers-v2-api-teams';
import retrieve_roles_v2_api_teams from './api/v2/teams/retrieve-roles-v2-api-teams';
import create_v2_api_templates from './api/v2/templates/create-v2-api-templates';
import list_v2_api_templates from './api/v2/templates/list-v2-api-templates';
import delete_v2_api_templates from './api/v2/templates/delete-v2-api-templates';
import create_v2_api_tokens from './api/v2/tokens/create-v2-api-tokens';
import retrieve_v2_api_tokens from './api/v2/tokens/retrieve-v2-api-tokens';
import update_v2_api_tokens from './api/v2/tokens/update-v2-api-tokens';
import list_v2_api_tokens from './api/v2/tokens/list-v2-api-tokens';
import delete_v2_api_tokens from './api/v2/tokens/delete-v2-api-tokens';
import reset_v2_api_tokens from './api/v2/tokens/reset-v2-api-tokens';
import retrieve_v2_api_usage from './api/v2/usage/retrieve-v2-api-usage';
import retrieve_data_export_events_v2_api_usage from './api/v2/usage/retrieve-data-export-events-v2-api-usage';
import retrieve_experimentation_keys_v2_api_usage from './api/v2/usage/retrieve-experimentation-keys-v2-api-usage';
import retrieve_experimentation_units_v2_api_usage from './api/v2/usage/retrieve-experimentation-units-v2-api-usage';
import retrieve_service_connections_v2_api_usage from './api/v2/usage/retrieve-service-connections-v2-api-usage';
import list_usage_v2_api_mau from './api/v2/usage/mau/list-usage-v2-api-mau';
import retrieve_bycategory_usage_v2_api_mau from './api/v2/usage/mau/retrieve-bycategory-usage-v2-api-mau';
import retrieve_sdks_usage_v2_api_mau from './api/v2/usage/mau/retrieve-sdks-usage-v2-api-mau';
import retrieve_usage_v2_api_streams from './api/v2/usage/streams/retrieve-usage-v2-api-streams';
import retrieve_bysdkversion_usage_v2_api_streams from './api/v2/usage/streams/retrieve-bysdkversion-usage-v2-api-streams';
import retrieve_sdkversions_usage_v2_api_streams from './api/v2/usage/streams/retrieve-sdkversions-usage-v2-api-streams';
import retrieve_v2_api_users from './api/v2/users/retrieve-v2-api-users';
import delete_v2_api_users from './api/v2/users/delete-v2-api-users';
import retrieve_users_v2_api_flags from './api/v2/users/flags/retrieve-users-v2-api-flags';
import update_users_v2_api_flags from './api/v2/users/flags/update-users-v2-api-flags';
import list_users_v2_api_flags from './api/v2/users/flags/list-users-v2-api-flags';
import retrieve_users_v2_api_expiring_user_targets from './api/v2/users/expiring-user-targets/retrieve-users-v2-api-expiring-user-targets';
import update_users_v2_api_expiring_user_targets from './api/v2/users/expiring-user-targets/update-users-v2-api-expiring-user-targets';
import create_v2_api_webhooks from './api/v2/webhooks/create-v2-api-webhooks';
import retrieve_v2_api_webhooks from './api/v2/webhooks/retrieve-v2-api-webhooks';
import update_v2_api_webhooks from './api/v2/webhooks/update-v2-api-webhooks';
import list_v2_api_webhooks from './api/v2/webhooks/list-v2-api-webhooks';
import delete_v2_api_webhooks from './api/v2/webhooks/delete-v2-api-webhooks';
import create_v2_api_announcements from './api/v2/announcements/create-v2-api-announcements';
import update_v2_api_announcements from './api/v2/announcements/update-v2-api-announcements';
import list_v2_api_announcements from './api/v2/announcements/list-v2-api-announcements';
import delete_v2_api_announcements from './api/v2/announcements/delete-v2-api-announcements';
import deployment_events_v2_api_engineering_insights from './api/v2/engineering-insights/deployment-events-v2-api-engineering-insights';
import retrieve_flag_events_v2_api_engineering_insights from './api/v2/engineering-insights/retrieve-flag-events-v2-api-engineering-insights';
import retrieve_pull_requests_v2_api_engineering_insights from './api/v2/engineering-insights/retrieve-pull-requests-v2-api-engineering-insights';
import retrieve_lead_time_engineering_insights_v2_api_charts from './api/v2/engineering-insights/charts/retrieve-lead-time-engineering-insights-v2-api-charts';
import retrieve_frequency_charts_engineering_insights_v2_api_deployments from './api/v2/engineering-insights/charts/deployments/retrieve-frequency-charts-engineering-insights-v2-api-deployments';
import retrieve_stale_charts_engineering_insights_v2_api_flags from './api/v2/engineering-insights/charts/flags/retrieve-stale-charts-engineering-insights-v2-api-flags';
import retrieve_status_charts_engineering_insights_v2_api_flags from './api/v2/engineering-insights/charts/flags/retrieve-status-charts-engineering-insights-v2-api-flags';
import retrieve_frequency_charts_engineering_insights_v2_api_releases from './api/v2/engineering-insights/charts/releases/retrieve-frequency-charts-engineering-insights-v2-api-releases';
import retrieve_engineering_insights_v2_api_deployments from './api/v2/engineering-insights/deployments/retrieve-engineering-insights-v2-api-deployments';
import update_engineering_insights_v2_api_deployments from './api/v2/engineering-insights/deployments/update-engineering-insights-v2-api-deployments';
import list_engineering_insights_v2_api_deployments from './api/v2/engineering-insights/deployments/list-engineering-insights-v2-api-deployments';
import group_engineering_insights_v2_api_insights from './api/v2/engineering-insights/insights/group-engineering-insights-v2-api-insights';
import retrieve_scores_engineering_insights_v2_api_insights from './api/v2/engineering-insights/insights/retrieve-scores-engineering-insights-v2-api-insights';
import retrieve_insights_engineering_insights_v2_api_groups from './api/v2/engineering-insights/insights/groups/retrieve-insights-engineering-insights-v2-api-groups';
import update_insights_engineering_insights_v2_api_groups from './api/v2/engineering-insights/insights/groups/update-insights-engineering-insights-v2-api-groups';
import list_insights_engineering_insights_v2_api_groups from './api/v2/engineering-insights/insights/groups/list-insights-engineering-insights-v2-api-groups';
import delete_insights_engineering_insights_v2_api_groups from './api/v2/engineering-insights/insights/groups/delete-insights-engineering-insights-v2-api-groups';
import list_engineering_insights_v2_api_repositories from './api/v2/engineering-insights/repositories/list-engineering-insights-v2-api-repositories';
import create_repositories_engineering_insights_v2_api_projects from './api/v2/engineering-insights/repositories/projects/create-repositories-engineering-insights-v2-api-projects';
import delete_repositories_engineering_insights_v2_api_projects from './api/v2/engineering-insights/repositories/projects/delete-repositories-engineering-insights-v2-api-projects';

export const endpoints: Endpoint[] = [];

function addEndpoint(endpoint: Endpoint) {
  endpoints.push(endpoint);
}

addEndpoint(retrieve_api_v2);
addEndpoint(list_api_v2);
addEndpoint(retrieve_caller_identity_api_v2);
addEndpoint(retrieve_openapi_json_api_v2);
addEndpoint(retrieve_public_ip_list_api_v2);
addEndpoint(retrieve_tags_api_v2);
addEndpoint(retrieve_versions_api_v2);
addEndpoint(retrieve_account_v2_api_relay_auto_configs);
addEndpoint(update_account_v2_api_relay_auto_configs);
addEndpoint(delete_account_v2_api_relay_auto_configs);
addEndpoint(relay_auto_configs_account_v2_api_relay_auto_configs);
addEndpoint(reset_account_v2_api_relay_auto_configs);
addEndpoint(retrieve_relay_auto_configs_account_v2_api_relay_auto_configs);
addEndpoint(retrieve_v2_api_applications);
addEndpoint(update_v2_api_applications);
addEndpoint(list_v2_api_applications);
addEndpoint(delete_v2_api_applications);
addEndpoint(update_applications_v2_api_versions);
addEndpoint(list_applications_v2_api_versions);
addEndpoint(delete_applications_v2_api_versions);
addEndpoint(retrieve_v2_api_approval_requests);
addEndpoint(update_v2_api_approval_requests);
addEndpoint(delete_v2_api_approval_requests);
addEndpoint(apply_v2_api_approval_requests);
addEndpoint(approval_requests_v2_api_approval_requests);
addEndpoint(retrieve_approval_requests_v2_api_approval_requests);
addEndpoint(reviews_v2_api_approval_requests);
addEndpoint(create_v2_api_auditlog);
addEndpoint(retrieve_v2_api_auditlog);
addEndpoint(list_v2_api_auditlog);
addEndpoint(retrieve_extinctions_v2_api_code_refs);
addEndpoint(create_code_refs_v2_api_repositories);
addEndpoint(retrieve_code_refs_v2_api_repositories);
addEndpoint(update_code_refs_v2_api_repositories);
addEndpoint(list_code_refs_v2_api_repositories);
addEndpoint(delete_code_refs_v2_api_repositories);
addEndpoint(branch_delete_tasks_code_refs_v2_api_repositories);
addEndpoint(retrieve_repositories_code_refs_v2_api_branches);
addEndpoint(update_repositories_code_refs_v2_api_branches);
addEndpoint(list_repositories_code_refs_v2_api_branches);
addEndpoint(extinction_events_repositories_code_refs_v2_api_branches);
addEndpoint(retrieve_code_refs_v2_api_statistics);
addEndpoint(list_code_refs_v2_api_statistics);
addEndpoint(retrieve_v2_api_destinations);
addEndpoint(update_v2_api_destinations);
addEndpoint(list_v2_api_destinations);
addEndpoint(delete_v2_api_destinations);
addEndpoint(generate_warehouse_destination_key_pair_v2_api_destinations);
addEndpoint(retrieve_projects_flag_links_v2_api_flags);
addEndpoint(update_projects_flag_links_v2_api_flags);
addEndpoint(delete_projects_flag_links_v2_api_flags);
addEndpoint(retrieve_v2_api_flag_statuses);
addEndpoint(retrieve_v2_api_flags);
addEndpoint(update_v2_api_flags);
addEndpoint(delete_v2_api_flags);
addEndpoint(copy_v2_api_flags);
addEndpoint(retrieve_dependent_flags_flags_v2_api_dependent_flags);
addEndpoint(retrieve_flags_v2_api_expiring_targets);
addEndpoint(update_flags_v2_api_expiring_targets);
addEndpoint(retrieve_flags_v2_api_expiring_user_targets);
addEndpoint(update_flags_v2_api_expiring_user_targets);
addEndpoint(retrieve_flags_v2_api_triggers);
addEndpoint(update_flags_v2_api_triggers);
addEndpoint(delete_flags_v2_api_triggers);
addEndpoint(list_flags_v2_api_release);
addEndpoint(delete_all_flags_v2_api_release);
addEndpoint(patch_all_flags_v2_api_release);
addEndpoint(retrieve_integration_capabilities_v2_api_big_segment_store);
addEndpoint(update_integration_capabilities_v2_api_big_segment_store);
addEndpoint(delete_integration_capabilities_v2_api_big_segment_store);
addEndpoint(retrieve_big_segment_store_integration_capabilities_v2_api_big_segment_store);
addEndpoint(retrieve_integration_capabilities_v2_api_feature_store);
addEndpoint(update_integration_capabilities_v2_api_feature_store);
addEndpoint(delete_integration_capabilities_v2_api_feature_store);
addEndpoint(retrieve_feature_store_integration_capabilities_v2_api_feature_store);
addEndpoint(validate_integration_capabilities_v2_api_feature_store);
addEndpoint(retrieve_integration_capabilities_v2_api_flag_import);
addEndpoint(update_integration_capabilities_v2_api_flag_import);
addEndpoint(delete_integration_capabilities_v2_api_flag_import);
addEndpoint(retrieve_flag_import_integration_capabilities_v2_api_flag_import);
addEndpoint(trigger_integration_capabilities_v2_api_flag_import);
addEndpoint(retrieve_v2_api_integration_configurations);
addEndpoint(update_v2_api_integration_configurations);
addEndpoint(delete_v2_api_integration_configurations);
addEndpoint(retrieve_integration_configurations_v2_api_keys);
addEndpoint(update_integration_configurations_v2_api_keys);
addEndpoint(retrieve_v2_api_integrations);
addEndpoint(update_v2_api_integrations);
addEndpoint(delete_v2_api_integrations);
addEndpoint(create_v2_api_members);
addEndpoint(retrieve_v2_api_members);
addEndpoint(update_v2_api_members);
addEndpoint(list_v2_api_members);
addEndpoint(delete_v2_api_members);
addEndpoint(patch_all_v2_api_members);
addEndpoint(teams_v2_api_members);
addEndpoint(retrieve_v2_api_metrics);
addEndpoint(update_v2_api_metrics);
addEndpoint(delete_v2_api_metrics);
addEndpoint(create_oauth_v2_api_clients);
addEndpoint(retrieve_oauth_v2_api_clients);
addEndpoint(update_oauth_v2_api_clients);
addEndpoint(list_oauth_v2_api_clients);
addEndpoint(delete_oauth_v2_api_clients);
addEndpoint(create_v2_api_projects);
addEndpoint(retrieve_v2_api_projects);
addEndpoint(update_v2_api_projects);
addEndpoint(list_v2_api_projects);
addEndpoint(delete_v2_api_projects);
addEndpoint(update_projects_v2_api_context_kinds);
addEndpoint(retrieve_context_kinds_projects_v2_api_context_kinds);
addEndpoint(create_projects_v2_api_environments);
addEndpoint(retrieve_projects_v2_api_environments);
addEndpoint(update_projects_v2_api_environments);
addEndpoint(list_projects_v2_api_environments);
addEndpoint(delete_projects_v2_api_environments);
addEndpoint(api_key_projects_v2_api_environments);
addEndpoint(mobile_key_projects_v2_api_environments);
addEndpoint(retrieve_followers_projects_v2_api_environments);
addEndpoint(retrieve_environments_projects_v2_api_context_attributes);
addEndpoint(retrieve_context_attributes_environments_projects_v2_api_context_attributes);
addEndpoint(retrieve_environments_projects_v2_api_context_instances);
addEndpoint(delete_environments_projects_v2_api_context_instances);
addEndpoint(search_environments_projects_v2_api_context_instances);
addEndpoint(retrieve_environments_projects_v2_api_contexts);
addEndpoint(update_environments_projects_v2_api_contexts);
addEndpoint(search_environments_projects_v2_api_contexts);
addEndpoint(create_environments_projects_v2_api_experiments);
addEndpoint(retrieve_environments_projects_v2_api_experiments);
addEndpoint(update_environments_projects_v2_api_experiments);
addEndpoint(list_environments_projects_v2_api_experiments);
addEndpoint(iterations_environments_projects_v2_api_experiments);
addEndpoint(retrieve_results_experiments_environments_projects_v2_api_metric_groups);
addEndpoint(retrieve_results_experiments_environments_projects_v2_api_metrics);
addEndpoint(evaluate_environments_projects_v2_api_flags);
addEndpoint(create_environments_projects_v2_api_holdouts);
addEndpoint(retrieve_environments_projects_v2_api_holdouts);
addEndpoint(update_environments_projects_v2_api_holdouts);
addEndpoint(list_environments_projects_v2_api_holdouts);
addEndpoint(evaluate_environments_projects_v2_api_segments);
addEndpoint(retrieve_experimentation_settings_projects_v2_api_experimentation_settings);
addEndpoint(update_experimentation_settings_projects_v2_api_experimentation_settings);
addEndpoint(retrieve_flag_defaults_projects_v2_api_flag_defaults);
addEndpoint(update_flag_defaults_projects_v2_api_flag_defaults);
addEndpoint(approval_requests_flag_copy_flags_projects_v2_api_environments);
addEndpoint(migration_safety_issues_flags_projects_v2_api_environments);
addEndpoint(retrieve_environments_flags_projects_v2_api_approval_requests);
addEndpoint(update_environments_flags_projects_v2_api_approval_requests);
addEndpoint(delete_environments_flags_projects_v2_api_approval_requests);
addEndpoint(apply_environments_flags_projects_v2_api_approval_requests);
addEndpoint(approval_requests_environments_flags_projects_v2_api_approval_requests);
addEndpoint(retrieve_approval_requests_environments_flags_projects_v2_api_approval_requests);
addEndpoint(reviews_environments_flags_projects_v2_api_approval_requests);
addEndpoint(update_environments_flags_projects_v2_api_followers);
addEndpoint(list_environments_flags_projects_v2_api_followers);
addEndpoint(delete_environments_flags_projects_v2_api_followers);
addEndpoint(retrieve_environments_flags_projects_v2_api_scheduled_changes);
addEndpoint(update_environments_flags_projects_v2_api_scheduled_changes);
addEndpoint(delete_environments_flags_projects_v2_api_scheduled_changes);
addEndpoint(retrieve_scheduled_changes_environments_flags_projects_v2_api_scheduled_changes);
addEndpoint(scheduled_changes_environments_flags_projects_v2_api_scheduled_changes);
addEndpoint(create_environments_flags_projects_v2_api_workflows);
addEndpoint(retrieve_environments_flags_projects_v2_api_workflows);
addEndpoint(list_environments_flags_projects_v2_api_workflows);
addEndpoint(delete_environments_flags_projects_v2_api_workflows);
addEndpoint(create_flags_projects_v2_api_release);
addEndpoint(update_flags_projects_v2_api_release);
addEndpoint(create_projects_v2_api_layers);
addEndpoint(update_projects_v2_api_layers);
addEndpoint(list_projects_v2_api_layers);
addEndpoint(retrieve_projects_v2_api_metric_groups);
addEndpoint(update_projects_v2_api_metric_groups);
addEndpoint(delete_projects_v2_api_metric_groups);
addEndpoint(metric_groups_projects_v2_api_metric_groups);
addEndpoint(retrieve_metric_groups_projects_v2_api_metric_groups);
addEndpoint(retrieve_projects_v2_api_release_pipelines);
addEndpoint(update_projects_v2_api_release_pipelines);
addEndpoint(delete_projects_v2_api_release_pipelines);
addEndpoint(release_pipelines_projects_v2_api_release_pipelines);
addEndpoint(retrieve_release_pipelines_projects_v2_api_release_pipelines);
addEndpoint(retrieve_releases_projects_v2_api_release_pipelines);
addEndpoint(retrieve_projects_v2_api_ai_configs);
addEndpoint(update_projects_v2_api_ai_configs);
addEndpoint(delete_projects_v2_api_ai_configs);
addEndpoint(ai_configs_projects_v2_api_ai_configs);
addEndpoint(retrieve_ai_configs_projects_v2_api_ai_configs);
addEndpoint(retrieve_metrics_projects_v2_api_ai_configs);
addEndpoint(retrieve_metrics_by_variation_projects_v2_api_ai_configs);
addEndpoint(create_ai_configs_projects_v2_api_variations);
addEndpoint(retrieve_ai_configs_projects_v2_api_variations);
addEndpoint(update_ai_configs_projects_v2_api_variations);
addEndpoint(delete_ai_configs_projects_v2_api_variations);
addEndpoint(retrieve_ai_configs_projects_v2_api_model_configs);
addEndpoint(delete_ai_configs_projects_v2_api_model_configs);
addEndpoint(model_configs_ai_configs_projects_v2_api_model_configs);
addEndpoint(retrieve_model_configs_ai_configs_projects_v2_api_model_configs);
addEndpoint(create_model_configs_ai_configs_projects_v2_api_restricted);
addEndpoint(delete_all_model_configs_ai_configs_projects_v2_api_restricted);
addEndpoint(create_v2_api_roles);
addEndpoint(retrieve_v2_api_roles);
addEndpoint(update_v2_api_roles);
addEndpoint(list_v2_api_roles);
addEndpoint(delete_v2_api_roles);
addEndpoint(retrieve_v2_api_segments);
addEndpoint(update_v2_api_segments);
addEndpoint(delete_v2_api_segments);
addEndpoint(create_segments_v2_api_contexts);
addEndpoint(retrieve_segments_v2_api_contexts);
addEndpoint(create_segments_v2_api_exports);
addEndpoint(retrieve_segments_v2_api_exports);
addEndpoint(create_segments_v2_api_imports);
addEndpoint(retrieve_segments_v2_api_imports);
addEndpoint(create_segments_v2_api_users);
addEndpoint(retrieve_segments_v2_api_users);
addEndpoint(retrieve_segments_v2_api_expiring_targets);
addEndpoint(update_segments_v2_api_expiring_targets);
addEndpoint(retrieve_segments_v2_api_expiring_user_targets);
addEndpoint(update_segments_v2_api_expiring_user_targets);
addEndpoint(create_v2_api_teams);
addEndpoint(retrieve_v2_api_teams);
addEndpoint(update_v2_api_teams);
addEndpoint(list_v2_api_teams);
addEndpoint(delete_v2_api_teams);
addEndpoint(members_v2_api_teams);
addEndpoint(patch_all_v2_api_teams);
addEndpoint(retrieve_maintainers_v2_api_teams);
addEndpoint(retrieve_roles_v2_api_teams);
addEndpoint(create_v2_api_templates);
addEndpoint(list_v2_api_templates);
addEndpoint(delete_v2_api_templates);
addEndpoint(create_v2_api_tokens);
addEndpoint(retrieve_v2_api_tokens);
addEndpoint(update_v2_api_tokens);
addEndpoint(list_v2_api_tokens);
addEndpoint(delete_v2_api_tokens);
addEndpoint(reset_v2_api_tokens);
addEndpoint(retrieve_v2_api_usage);
addEndpoint(retrieve_data_export_events_v2_api_usage);
addEndpoint(retrieve_experimentation_keys_v2_api_usage);
addEndpoint(retrieve_experimentation_units_v2_api_usage);
addEndpoint(retrieve_service_connections_v2_api_usage);
addEndpoint(list_usage_v2_api_mau);
addEndpoint(retrieve_bycategory_usage_v2_api_mau);
addEndpoint(retrieve_sdks_usage_v2_api_mau);
addEndpoint(retrieve_usage_v2_api_streams);
addEndpoint(retrieve_bysdkversion_usage_v2_api_streams);
addEndpoint(retrieve_sdkversions_usage_v2_api_streams);
addEndpoint(retrieve_v2_api_users);
addEndpoint(delete_v2_api_users);
addEndpoint(retrieve_users_v2_api_flags);
addEndpoint(update_users_v2_api_flags);
addEndpoint(list_users_v2_api_flags);
addEndpoint(retrieve_users_v2_api_expiring_user_targets);
addEndpoint(update_users_v2_api_expiring_user_targets);
addEndpoint(create_v2_api_webhooks);
addEndpoint(retrieve_v2_api_webhooks);
addEndpoint(update_v2_api_webhooks);
addEndpoint(list_v2_api_webhooks);
addEndpoint(delete_v2_api_webhooks);
addEndpoint(create_v2_api_announcements);
addEndpoint(update_v2_api_announcements);
addEndpoint(list_v2_api_announcements);
addEndpoint(delete_v2_api_announcements);
addEndpoint(deployment_events_v2_api_engineering_insights);
addEndpoint(retrieve_flag_events_v2_api_engineering_insights);
addEndpoint(retrieve_pull_requests_v2_api_engineering_insights);
addEndpoint(retrieve_lead_time_engineering_insights_v2_api_charts);
addEndpoint(retrieve_frequency_charts_engineering_insights_v2_api_deployments);
addEndpoint(retrieve_stale_charts_engineering_insights_v2_api_flags);
addEndpoint(retrieve_status_charts_engineering_insights_v2_api_flags);
addEndpoint(retrieve_frequency_charts_engineering_insights_v2_api_releases);
addEndpoint(retrieve_engineering_insights_v2_api_deployments);
addEndpoint(update_engineering_insights_v2_api_deployments);
addEndpoint(list_engineering_insights_v2_api_deployments);
addEndpoint(group_engineering_insights_v2_api_insights);
addEndpoint(retrieve_scores_engineering_insights_v2_api_insights);
addEndpoint(retrieve_insights_engineering_insights_v2_api_groups);
addEndpoint(update_insights_engineering_insights_v2_api_groups);
addEndpoint(list_insights_engineering_insights_v2_api_groups);
addEndpoint(delete_insights_engineering_insights_v2_api_groups);
addEndpoint(list_engineering_insights_v2_api_repositories);
addEndpoint(create_repositories_engineering_insights_v2_api_projects);
addEndpoint(delete_repositories_engineering_insights_v2_api_projects);

export type Filter = {
  type: 'resource' | 'operation' | 'tag' | 'tool';
  op: 'include' | 'exclude';
  value: string;
};

export function query(filters: Filter[], endpoints: Endpoint[]): Endpoint[] {
  const allExcludes = filters.length > 0 && filters.every((filter) => filter.op === 'exclude');
  const unmatchedFilters = new Set(filters);

  const filtered = endpoints.filter((endpoint: Endpoint) => {
    let included = false || allExcludes;

    for (const filter of filters) {
      if (match(filter, endpoint)) {
        unmatchedFilters.delete(filter);
        included = filter.op === 'include';
      }
    }

    return included;
  });

  // Check if any filters didn't match
  const unmatched = Array.from(unmatchedFilters).filter((f) => f.type === 'tool' || f.type === 'resource');
  if (unmatched.length > 0) {
    throw new Error(
      `The following filters did not match any endpoints: ${unmatched
        .map((f) => `${f.type}=${f.value}`)
        .join(', ')}`,
    );
  }

  return filtered;
}

function match({ type, value }: Filter, endpoint: Endpoint): boolean {
  switch (type) {
    case 'resource': {
      const regexStr = '^' + normalizeResource(value).replace(/\*/g, '.*') + '$';
      const regex = new RegExp(regexStr);
      return regex.test(normalizeResource(endpoint.metadata.resource));
    }
    case 'operation':
      return endpoint.metadata.operation === value;
    case 'tag':
      return endpoint.metadata.tags.includes(value);
    case 'tool':
      return endpoint.tool.name === value;
  }
}

function normalizeResource(resource: string): string {
  return resource.toLowerCase().replace(/[^a-z.*\-_]*/g, '');
}
